In [2]:
pip install numpy<2


Note: you may need to restart the kernel to use updated packages.


The system cannot find the file specified.


In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-95,   9,  71,  26,  60, -61])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.4, 0.6]])
tensor

tensor([[0.1000, 1.2000],
        [2.4000, 0.6000]])

In [4]:
zeros = torch.zeros(2, 3) # takes dimensio/size as input
zeros # outputs are floating point numbers

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# Ones function
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
# arrange function
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [7]:
linspace = torch.linspace(3, 11, steps = 5)
linspace

tensor([ 3.,  5.,  7.,  9., 11.])

In [8]:
logspace = torch.logspace(start = -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [9]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
a = torch.empty((2, 3), dtype = torch.int64)
a

tensor([[0, 0, 0],
        [0, 0, 0]])

In [11]:
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

## CPU vs GPU

In [2]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'CPU'
device

'CPU'

In [2]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0000000000
CPU times: total: 0 ns
Wall time: 0 ns


In [11]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"GPU: {elapsed_time:.10f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"CPU: {elapsed_time:.10f}")

GPU: 0.0349438190
CPU: 0.1642460823


## Some more examples of torch

1. torch.stack()
2. torch.multinomial
3. torch.tril
4. torch.triu
5. torch.T/ input.Transpose
6. nn.Linear
7. torch.cat
8. F.softmax

**1. Multinomial**

In [9]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 10 samples from the multinomial distribution.
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**2. torch.cat (contancinate)**

In [13]:
tensor = torch.tensor([1, 2, 3, 4])
cat = torch.cat((tensor, torch.tensor([5])), dim=0)
cat

tensor([1, 2, 3, 4, 5])

**3. torch.tril (lower matrix)**

In [23]:
a = torch.randn(5, 5)
a
left_matrix = torch.tril(a)
print(f"with a:\n {left_matrix}")
left_matrix = torch.tril(torch.ones(5, 5))
print(f"without a/ with ones matrix:\n {left_matrix}")

with a:
 tensor([[-1.3733,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.7870, -1.5850,  0.0000,  0.0000,  0.0000],
        [-0.1370, -0.7798, -0.1194,  0.0000,  0.0000],
        [-0.7516,  0.5230, -0.0352,  0.8854,  0.0000],
        [-0.3934,  0.1471, -1.6231, -0.5835,  0.0260]])
without a/ with ones matrix:
 tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


**4. torch.triu (upper matrix)**

In [24]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [25]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [26]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

**5. transpose function**

In [31]:
input = torch.zeros(2, 3, 4)
one = input.transpose(0, 2)    # flip the oth (zero-th) position with the 2nd posisiton.
one.shape

torch.Size([4, 3, 2])

**6. torch.stack()**

In [34]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack these tensor together in a new dimension
final_tensor = torch.stack([tensor1, tensor2, tensor3])
final_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**7.nn.linear function**

In [35]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([ 6.4322, 11.0617, -4.1140], grad_fn=<SqueezeBackward4>)

**8.Softmax function**

In [36]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1., 2., 3.])

# Apply softmax using nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

## nn.Embeddings

In [37]:
# Initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indicies = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indicies)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensianality of the embedding vector
embedded_output.shape

torch.Size([4, 100])

## matrix multiplication

In [41]:
a = torch.tensor([[1, 2], [4, 6], [9, 10]])
b = torch.tensor([[7, 8, 9], [10, 12, 11]])

# print(a @ b)
print(torch.matmul(a, b)) # does the same thing as of above

tensor([[ 27,  32,  31],
        [ 88, 104, 102],
        [163, 192, 191]])


In [47]:
# type int_64
int_64 = torch.randint(2, (3, 2)).float()
# type_float_32
float_32 = torch.rand(2, 3)
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
result

tensor([[0.3991, 0.3056, 0.1187],
        [0.7957, 0.4801, 0.6980],
        [1.1947, 0.7857, 0.8167]])